name = "youtube-live-bot"
main = "index.js"
compatibility_date = "2024-02-04"
node_compat = true

[triggers]
crons = ["*/15 * * * *"]

[[kv_namespaces]]
binding = "DB"
id = "5262d9a6b1ac41dfaf93f43e35ef6e29"
preview_id = "TODO_REPLACE_WITH_YOUR_KV_PREVIEW_ID"
